### ISSUE TITLE
02.05.01 Profile picture deterministically generated from profile name if no uploaded profile image.

### ISSUE THREAD

**Issue by trinitythai** [CMPUT301W24T09/fire-and-based#11]
## Description

Profile picture deterministically generated from profile name if no uploaded profile image.

## Acceptance criteria

- wiki entry 
- registration page --> user doesn't upload image 
- user id and name used to deterministically generate profile picture
- limited to certain characters for user id

**Comment by amitch747** [comment]
Side note for myself. Automatic profile picture needs to be its own field within the user object. Another field will hold the uploaded profile pictures. That way if a profile picture if deleted by a user or admin, the default/automatic profile picture will still be there.
