### ISSUE TITLE
02.02.01 I want to upload a profile picture for a more personalized experience.

### ISSUE THREAD

**Issue by trinitythai** [CMPUT301W24T09/fire-and-based#20]
## Description 

I want to upload a profile picture for a more personalized experience.

## Acceptance criteria

- can do this when either first registering or editing their profile
- register new user page, click on empty image/plus icon button and upload image 
- edit profile page,  click on empty image/plus icon button and upload image 
- wiki entry

**Comment by amitch747** [comment]
GOT IT WORKING YEAHHHHHHHHHHHHHHHHHHHHHHHHH.

Later on I'll tweak it so the images upload with the correct name. If its a user it'll be the device id. If its an organizer it'll be the device id with an addition of either QR or POSTER
