### ISSUE TITLE
04.03.01 Be able to remove images

### ISSUE THREAD

**Issue by TylerBeach** [CMPUT301W24T09/fire-and-based#21]
## Description
- Upon selecting/viewing an image, administrator has the ability to delete if deemed inappropriate/provides no purpose

## Acceptance Criteria
- Button allowing for deletion of images from Firebase
- wiki entry 
- view all images uploaded onto the app 
- will be able to view clicked image and then provided with button to delete
- see who uploaded the image

**Comment by amitch747** [comment]
done works
