### ISSUE TITLE
Infinite loading screen on first load

### ISSUE THREAD

**Issue by Ilya-Nalivaiko** [CMPUT301W24T09/fire-and-based#53]
User gets added to db successfully and closing and reopening app works, it just doesn't close the loading screen that first time

**Comment by ssskii** [comment]
Fixed - Intent is now created and started when no device id is found within the users device

**Comment by ghost** [comment]
Fixed - Intent is now created and started when no device id is found within the users device

**Comment by TylerBeach** [comment]
Bug is now fixed no need to reload/install app
